# Fichier listant les paramètres du module et leurs valeurs par défaut
# Code du module utilisé dans les URL et les commandes GeoNature
module_code="cs"
# Titre du module utilisé pour l'affichage
module_title="Stratégie Conservation"
